title: "Colin Fleming"
email: c3flemin@gmail.com
baseurl: "/"
description: An Internet

url: "https://colinxfleming.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: colinxfleming
linkedin_username: colinxfleming

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass

# Default excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run.sh

collections_dir: collections
collections:
  - posts
  - projects
  - talks

show_excerpts: false
