title: "Colin Fleming"
email: c3flemin@gmail.com
description: >-
  Hey, y'all like posting?
  Personal site for Colin Fleming, a web and data engineer. Specializes in
  Ruby, SQL, Python, with some JavaScript and CSS thrown in for good measure.
  Project lead at DCAF Engineering, former board member of the DC Abortion
  Fund.
baseurl: "/"
url: "https://colinxfleming.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: colinxfleming

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass

# Default excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run.sh

collections_dir: collections
collections:
  - posts
  - projects
  - talks

show_excerpts: true
